export function isObject(value: any, ignoreArray: boolean): boolean;
export function isNumber(value: any): boolean;
export function isString(value: any): boolean;
export function isFunction(value: any): boolean;
export function isArray(value: any): boolean;
export function isNull(value: any): boolean;
export function isUndefined(value: any): boolean;
export function extend(...items: any[]): any;
export function random(max?: number, min?: number): number;
export function randInt(max?: number, min?: number): number;
